### ISSUE TITLE
Error when running version version 1.1.0

### ISSUE THREAD

**Issue by thorgas** [TrueLayer/truelayer-react-native-sdk#35]
Hi,
when installing the SDK via yarn I and running npx react-native run-ios get the following error:
error: Error: While trying to resolve module `rn-truelayer-payments-sdk` from file `/Users/***/worktrees/src/screens/Transactions/TransactionItemScreen/AuthToOtherBankPaymentConfirmation.tsx`, the package `/Users/***/worktrees/node_modules/rn-truelayer-payments-sdk/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/***/worktrees/node_modules/rn-truelayer-payments-sdk/js/index`. Indeed, none of these files exist:

  * /Users/***/worktrees/node_modules/rn-truelayer-payments-sdk/js/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)

**Comment by TheInkedEngineer** [comment]
@thorgas apologies as we did not notice this issue until today. We are working on a fix in #45 and will be released in 1.2.0 coming later this week.
