### ISSUE TITLE
Incompatible with platform version from fresh RN project

### ISSUE THREAD

**Issue by olessavluk** [TrueLayer/truelayer-react-native-sdk#70]
Hey, tried to install this package in freshly generated RN project and on `pod install` it fails with error:
```
[!] CocoaPods could not find compatible versions for pod "rn-truelayer-payments-sdk":
  In Podfile:
    rn-truelayer-payments-sdk (from `../node_modules/rn-truelayer-payments-sdk`)

Specs satisfying the `rn-truelayer-payments-sdk (from `../node_modules/rn-truelayer-payments-sdk`)` dependency were found, but they required a higher minimum deployment target.
```

What is advised workaround for this?

**Comment by tl-daven-gomes** [comment]
Hi, a freshly generated React Native project usually has a minimum deployment target less than the TrueLayer SDK's minimum of iOS 14.0 and above. You can change the Podfile in `ios/Podfile` to accept iOS 14.0 from:

```
platform :ios, min_ios_version_supported
```

to:
```
platform :ios, 14.0
```

There's more information on this thread [here](https://github.com/stripe/stripe-react-native/issues/1280#issue-1566547155), as well as where `min_ios_version_supported` is set by React Native.

**Comment by olessavluk** [comment]
Yeah, that works, thanks

This however makes app incompatible with iOS <= 14 [which can be up to 3% of users globally](https://iosref.com/ios-usage)

**Comment by tl-daven-gomes** [comment]
Unfortunately we don't have any plans to support less than iOS 14 in the near future as we use some APIs that require this. I'll pass on your feedback. Thanks!
